# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.provider.smtp:
        class: App\Provider\SmtpProvider
        public: true

    app.provider.ses:
        class: App\Provider\SesProvider
        public: true

    app.service.notification.smtp:
        class: App\Service\NotificationService
        public: true
        calls:
            - [setSmtp, ['@app.provider.smtp']]

    app.service.notification.ses:
        class: App\Service\NotificationService
        public: true
        calls:
            - [setSes, ['@app.provider.ses']]

    console.command:
        class: App\Command\SendNotificationCommand
        public: true
